/*
 * Addresses
 *
 * The Addresses API validates and corrects address information, eliminating errors, improving package delivery service and package pricing. This suite of APIs provides different utilities for addressing components. The ZIP Code&#8482; lookup finds valid ZIP Code&#8482; for a City and State.  The City/State lookup provides the valid cities and states for a provided ZIP Code&#8482;.  The Address Standardization API validates and standardizes USPS&#174; domestic addresses, city and state names, and ZIP Code&#8482; in accordance with USPS&#174; addressing standards.  The USPS&#174; address standard includes the ZIP + 4&#174;, signifying a USPS&#174; delivery point, given a street address, a city and a state. 
 *
 * The version of the OpenAPI document: 3.0.2
 * Contact: APISupport@usps.gov
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddressAdditionalInfoDpvConfirmation : The DPV Confirmation Indicator is the primary method used by the USPS® to determine whether an address was considered deliverable or undeliverable.
/// The DPV Confirmation Indicator is the primary method used by the USPS® to determine whether an address was considered deliverable or undeliverable.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddressAdditionalInfoDpvConfirmation {
    /// Address was DPV confirmed for both primary and (if present) secondary numbers.
    String(String),
    /// Address was DPV confirmed for the primary number only, and the secondary number information was missing.
    String(String),
    /// Address was DPV confirmed for the primary number only, and the secondary number information was present but not confirmed.
    String(String),
    /// Both primary and (if present) secondary number information failed to DPV confirm.
    String(String),
}

impl Default for AddressAdditionalInfoDpvConfirmation {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

